### ISSUE TITLE
Character encoding issue with foreign char "ã"

### ISSUE THREAD

**Issue by joao-neves95** [rubicon-oss/LicenseHeaderManager#101]
Hello, it seems that the extension has an encoding issue.

My first name (in Portuguese from Portugal) is "João", but when the header gets played, a "�" char is inserted in the place of the "ã".

Nice extension BTW, it's very helpful

**Comment by FlorianDecker** [comment]
Hi!

Thanks for the info!

I guess you created a solution level header definition file (the .licenseheader file in the file system is in the same folder hierarchie as your solution) ?

This is a known problem, also already fixed (#95 ), but sadly not yet released.
You can probably fix it on your end by changing the encoding of the .licenseheader file manually to UTF8.

Best Regards,
Florian

**Comment by joao-neves95** [comment]
Thank you for your response.
Sorry for the duplicate, I didn't find the issue you linked.
I've just changed the encoding to UTF-8 and it's all working as expected now.

Best regards,
João
