### ISSUE TITLE
adding headers to .cshtml files

### ISSUE THREAD

**Issue by mtallamy** [rubicon-oss/LicenseHeaderManager#106]
I'm struggling to get the LicenseHeaderManager to insert headers into .cshtml files. I've tried this in a new web application and can confirm the header population is working for other file types, e.g. .cs or .js

Any thoughts?

**Comment by Stefan-Ilic** [comment]
In Visual Studio, if you navigate to Tools->Options->License Header Manager->Languages, you can define file extensions for which the License Header Manager should be enabled. Add an entry for .cshtml and set "Begin Comment" and "End Comment" (e.g. `@*` and `*@`). Edit the .licenseheader file accordingly. We will add this to the default settings in a future release, but for now it will do the trick.

**Comment by FlorianDecker** [comment]
When we add the next set of File Extensions to the default Language Settings we should also consider to implement a warning when there is a file extension used in the licenseheader file which has no respective setting in the Language Settings page (see #48 )

**Comment by mtallamy** [comment]
> In Visual Studio, if you navigate to Tools->Options->License Header Manager->Languages, you can define file extensions for which the License Header Manager should be enabled. Add an entry for .cshtml and set "Begin Comment" and "End Comment" (e.g. `@*` and `*@`). Edit the .licenseheader file accordingly. We will add this to the default settings in a future release, but for now it will do the trick.

That's great! Many thanks.
