### ISSUE TITLE
Linked commands are not being saved/loaded

### ISSUE THREAD

**Issue by Stefan-Ilic** [rubicon-oss/LicenseHeaderManager#108]
Bumping the `Microsoft.VisualStudio.Shell` version from 10.0 to 14.0 in the latest release caused linked commands to not be saved/loaded after a Visual Studio restart. According to [this](https://stackoverflow.com/questions/32751040/store-array-in-options-using-dialogpage#comment61223726_32808238), it is caused by implementation changes in `DialogPage.LoadSettingsFromStorage` and `SaveSettingsToStorage`, causing properties using `TypeConverter` to not be saved and loaded. Decompiling the  `Microsoft.VisualStudio.Shell` assemblies confirmed these changes.

This appears to be fixable by manually invoking `TypeConverter` and saving its result, as seen in the linked stackoverflow answer.

**Comment by FlorianDecker** [comment]
Also, it seems that with the new Upgrade, the Settings are saved in a different location. Therefore we had to  implement a Migration Step, moving the Settings from the old to the new location
