### ISSUE TITLE
Adding new LinkedCommands requires a visual studio restart

### ISSUE THREAD

**Issue by Stefan-Ilic** [rubicon-oss/LicenseHeaderManager#111]
When linking a command via `Options->License Header Manager->General`, the new command requires a restart in order to work. Unfortunately, the new serialization properties do not call the `LinkedCommand` setter,  preventing the registration of required events from happening. The apparent solution is to simply make sure the setter of `LinkedCommand` is called by `LinkedCommandSerialized`.

**Comment by FlorianDecker** [comment]
Fixed in 808a60
