### ISSUE TITLE
Year range based on last written year

### ISSUE THREAD

**Issue by Mrxx99** [rubicon-oss/LicenseHeaderManager#113]
Since often it is required to give a range for the years. e.g "2015-2019" it would be useful if this could be done automatically. I know there is the option of %CreationYear% but that won't work often, if you copied a file or this can be lost through getting from source control.

I think the best solution would be if the current set year in the file header get's read, and if it is lower a range will get applied.

For example:
Current file header:
`// Copyright (c) Sample AG 2015`

would be transformed when applied to
`// Copyright (c) Sample AG 2015-2019`

the same result should appear if the header looks like this:
`// Copyright (c) Sample AG 2015-2017`

For this a new Expendable Propertiy, like %YearRange%

**Comment by Stefan-Ilic** [comment]
Hi @Mrxx99,

This indeed sounds like an idea that could be useful. The problem, however, is that it does not fit into our current concept. At the moment, it is not possible to retrieve information from an already existing license header. The header-insertion itself would need to have logic of its own.

This would require a major concept overhaul that we are not prepared to have right now. As a result, I sadly have to mark your issue as `won't fix`.

Hopefully, you can achieve the functionality you are looking for by other means.

Cheers,
Stefan

**Comment by stefan-wenig** [comment]
May I offer some advice here? Years ago I consulted Legal about the same problem and learned that the year range in a (c) note offers absolutely no additional legal value. Their suggestion was to just remove it, and that's what we did for all our company's source files. Less merge issues too.
