### ISSUE TITLE
Possibility to skip a single file name

### ISSUE THREAD

**Issue by VPKSoft** [rubicon-oss/LicenseHeaderManager#114]
Is there a possibility to skip a license header from a single file?
If not the possibility would be greatly appreciated. This would be useful I.e. in case of a common file/gist which is released to public domain and already has a license header not to be re-licensed.

**Comment by Stefan-Ilic** [comment]
Hi @VPKSoft,

If the files you wish to ignore have a certain sub-extension, like `.gist.js`, you can add and empty license header definition in your .licenseheader file e.g. 

```
extensions: .js
// I am a license header for usual .js files
extensions: .gist.js
extensions: .cs
// the extension above me has no license header
```
This won't remove any license headers that may already have been added to your `.gist.js` file, but it will skip it next time license headers are applied.

I hope this solution works for you.

Cheers,
Stefan

**Comment by VPKSoft** [comment]
Okay,
I'll do the renaming thing then. Thank you for the great software!
But in the further development a single file exclusion should be considered.

**Comment by Stefan-Ilic** [comment]
A follow-up feature request issue has been created (#115).
