### ISSUE TITLE
Add "Created By"?

### ISSUE THREAD

**Issue by MagicHatJo** [rubicon-oss/LicenseHeaderManager#117]
Hi,

Would it be possible to add an expansion for creator/author name? Currently, the docs only show that last modified name is implemented.

Thanks

**Comment by FlorianDecker** [comment]
Hi!

Thanks for the suggestion! We already have the issue https://github.com/rubicon-oss/LicenseHeaderManager/issues/98, which discusses this feature on a broader scope, containing some thoughts on a design making this possible.

If you have new ideas, or want to contribute that feature with a pull request, feel free to discuss the details there.

I am gonne close this one as duplicate.

Best Regards,
Florian
