### ISSUE TITLE
LicenseHeaderManager doenst work on VS 19 on mac (.vsix) dont even show in mac 

### ISSUE THREAD

**Issue by harschell** [rubicon-oss/LicenseHeaderManager#119]
LicenseHeaderManager doenst work on VS 19 on mac (.vsix) dont even show in mac I assume there's different extension for mac.
Do let us know when LicenseHeaderManager will support VS19 on mac or any other alternative.

**Comment by MichaelKetting** [comment]
Thank you for your interest ist Mac. Please see #99 for the discussion about this topic. I'm closing the current issue as a duplicate.
