### ISSUE TITLE
Exclude folders?

### ISSUE THREAD

**Issue by scheelings** [rubicon-oss/LicenseHeaderManager#120]
Is it possible to exclude folders from the License Manager? In my case all files within the node_modules folder are included, but this should be excluded.

**Comment by MichaelKetting** [comment]
Hello @scheelings, yes, you can simply put a licenseheader-file into the folder with an empty license directive: 
`extensions: .js`
You will still need to list all the extensions of the files to skip.

See also https://github.com/rubicon-oss/LicenseHeaderManager/wiki/License-Header-Definitions for a bit more text on exluding files.
