### ISSUE TITLE
Find In Files dialog, ALT-L keyboard shortcut seems to be hijacked by License Header Manager

### ISSUE THREAD

**Issue by bobk2824** [rubicon-oss/LicenseHeaderManager#124]
If I have License Header Manager loaded, and in my C++ project I type: SHIFT-CTRL-F (for Find in Files), Then I hit ALT-L. That should bring me to the "Look In" field. It does nothing.

The way I figured out this was because of License Header Manager was I created a bare-bones C++ project and brought up Find in Files. When I hit ALT-L, i get this warning:

---------------------------
Error
---------------------------
No license header definition file found in project Project1.
Do you want to add a new License Header Definition File?
---------------------------
Yes   No   
---------------------------

Is there any way to get ALT-L to work?
Thanks.

**Comment by Stefan-Ilic** [comment]
Hi @bobk2824,

LicenseHeaderManager uses `ALT + L` for its "AddLicenseHeader" command, but you can override it by doing the following:

* In Visual Studio navigate to Tools => Options, the options window should pop up
* Then in your options window, expand "Environment" and navigate to "Keyboard"
* In the "Show commands containing" field type "Edit.AddLicenseHeader"
* There, you can see that the command is using `ALT + L` as its shortcut
* Hit "Remove" to unbind the shortcut from the command
* `ALT + L` should behave as you would expect it to now

![image](https://user-images.githubusercontent.com/24362621/89389771-1f1d2200-d706-11ea-91a4-ee6e205bba04.png)

I hope I was able to help.

Best regards,
Stefan

**Comment by bobk2824** [comment]
Thanks!
