### ISSUE TITLE
How can I set up it does not remove others' comments at the top file?

### ISSUE THREAD

**Issue by thangl3** [rubicon-oss/LicenseHeaderManager#126]
My problem as the title. An example I have a comment of Task runner binding like that 
`/// <binding AfterBuild='default' />`. When I am saving that file, it always removes my bidding comment tag. Task runner can not detected my gulp file.
Please help me.

**Comment by thangl3** [comment]
I have found the solution. Now I posted here, for someone who looks an answer. We need to use [Skip expressions](https://github.com/rubicon-oss/LicenseHeaderManager/wiki/Skip-Expressions)

Add this Expressions to this box:

```
((/// *<binding.*/>( |\t)*(\n|\r\n|\r)?)*)|((/// *<reference.*/>( |\t)*(\n|\r\n|\r)?)*)
```

![image](https://user-images.githubusercontent.com/15165794/90483905-aa170700-e15f-11ea-9a87-e633f66faa6c.png)

**Comment by Stefan-Ilic** [comment]
Hi @thangl3,

I'm glad you were able to find the answer yourself. Since everything is sorted out, I'll be closing the issue then.

Best regards,
Stefan Ilic
