### ISSUE TITLE
holder headers not removed

### ISSUE THREAD

**Issue by bvarillo** [rubicon-oss/LicenseHeaderManager#138]
I am currently working with VS Code on ubuntu and when I use the command "Add License Header" to apply modification done in .lict the new header is inserted in top of the old one instead of replacing it. So it end with two license header in each files.

I am using the 1.55.2 version of VSC on Ubuntu 20.04

**Comment by Stefan-Ilic** [comment]
Hi @bvarillo,

I am admittedly a little confused by your error report. The stable version of LicenseHeaderManager is a Visual Studio extension that exclusively works with Visual Studio for Windows, and not Visual Studio Code. Are you telling me you found a way to also make it work with Visual Studio Code?

Best regards,
Stefan

**Comment by bvarillo** [comment]
I just realize that my issue is on the wrong project. I get confused by the fact that your extension has the exact same name than one made for VS Code [](https://marketplace.visualstudio.com/items?itemName=angelo-breuer.license-header-manager&ssr=false#overview).
Sorry for the inconvenience,
Best regads,
Benoit
