### ISSUE TITLE
Does the CreationMonth and CreationDay support long time format?

### ISSUE THREAD

**Issue by xiedongweo** [rubicon-oss/LicenseHeaderManager#139]
%CreationYear%-%CreationMonth%-%CreationDay%
It shows 2021-4-22

I want to make the date show like this 2021-04-22

**Comment by raffaelfoidl** [comment]
Hey,

sorry for the belated reply. Unfortunately, we do not have the necessary resources for precisely designing and implementing such a feature.

However, based on your suggestion, we have defined a rough sketch of how we envision a solution that would be right for us.

Please refer to #140  for more information. You (and anybody else) are welcome to submit a PR.


Kind regards,

Raffael
