### ISSUE TITLE
Support for Visual Studio 2022

### ISSUE THREAD

**Issue by jeroenlandheer** [rubicon-oss/LicenseHeaderManager#141]
Visual Studio 17 (2022) is now in preview. 

Besides changing the version info in this extension (in `source.extension.vsixmanifest`), I don't think there's much that needs to be changed.

Can this extension be updated so we can give this a try with the new preview of Visual Studio?

**Comment by MichaelKetting** [comment]
@jeroenlandheer I've made a note on this to look into it in July.

**Comment by GRXoft** [comment]
Now that Visual Studio 2022 officially launched, is there any chance of implementing this suggestion anytime soon?

**Comment by MichaelKetting** [comment]
@GRXoft it's on the list but I cannot make any promises regarding the schedule.

**Comment by wangkanai** [comment]
Any updates on for Visual Studio 2022 yet?

![image](https://user-images.githubusercontent.com/10666633/144691782-bce1758f-5c30-417a-904b-5614d8b4c4e0.png)

**Comment by Andy-Solo** [comment]
Why aren't you releasing this extension with VS 2022 support?

**Comment by AuBoulder** [comment]
[LicenseHeaderManager.zip](https://github.com/rubicon-oss/LicenseHeaderManager/files/7891221/LicenseHeaderManager.zip)

**Comment by iam-mholle** [comment]
I have opened a PR for this issue: https://github.com/rubicon-oss/LicenseHeaderManager/pull/166, development builds of the extension are attached (unsigned). The official release should happen in the beginning of february if no problems arise.

**Comment by AshuBanctec** [comment]
Any updates on the release to support VS 2022

**Comment by MichaelKetting** [comment]
@AshuBanctec we have just done the update in the VS gallery.
