### ISSUE TITLE
LicenseHeaderManager.Headers.UserInfo threw an exception

### ISSUE THREAD

**Issue by nielsvdc** [rubicon-oss/LicenseHeaderManager#16]
When pressing Alt-L to paste in the license header, I get a message "The type initializer for 'LicenseHeaderManager.Headers.UserInfo' threw an exception.
On further inspection the line in the UserInfo initializer with the code "UserPrincipal.Current.DisplayName" is probably the cause of the exception. I'm running VS on a home computer not connected to a domain. This line will throw an exception, because it cannot find a link to an AD.

**Comment by FlorianDecker** [comment]
Hi Niels!

Thanks for your detailed bug report. I could not reproduce it on my Home machine, which also isnt connected to a domain and sets the DisplayName correctly. Could you share which type of exception gets thrown?

Regards,
Florian

**Comment by nielsvdc** [comment]
"The type initializer for 'LicenseHeaderManager.Headers.UserInfo' threw an exception." is the only message I get. I'm unable to zoom in to the exception specifications.

**Comment by FlorianDecker** [comment]
Ok, thanks anyway. I will have a deeper look into this in our next Release (could take some time, we don't know a date yet)

**Comment by dsuess** [comment]
Receiving the same problem here on v1.6.2. I too am logged in under a domain account.
Also to note, that my solution is using a SAP (Shared Asset Project).  Thank you again for the awesome VS extension!!

**Comment by NigelWhatling** [comment]
I have this problem as well. I generally use two computers for development. The plugin has never worked from my laptop (connected via wifi) but has generally worked without fault from my wired workstation. Today the problem has no appeared on my workstation as well.

I am a domain user connected to my own local domain.

For reference, it's definitely **UserPrincipal.Current** (in the static constructor for UserInfo) that is causing the problem. It's throwing a **PrincipalServerDownException** ("The server could not be contacted.") with inner exception of **LdapException** ("The LDAP server is unavailable.").

I have cloned the source and am having a quick look around, but I ran into a dll mismatch targetting .NET v4.0. I've had to change the projects to target v4.5, so I can't be completely sure if anything I change will be a proper fix. Apparently there is a 'bug' in v4.5 with this code. Workaround seems to be to just repeat the call after the first failed attempt and it works.

**Comment by NigelWhatling** [comment]
Further to previous comment...

Since principal lookup cannot be guaranteed reliable, you definitely need some sort of fallback when failures occur. I still don't know why this started failing in my environment. Networking/security isn't really my specialty.  :(

I was able to modify the code and install a hacked version which at least works around the problem. First time use still causes a delay while it tries to contact the LDAP server. I've just set it to fall back to the standard username. Fortunately for me, I'm not using user display name anywhere.

```C#
static UserInfo()
{
    Name = Environment.UserName;

    try
    {
        DisplayName = UserPrincipal.Current.DisplayName;
    }
    catch (PrincipalServerDownException)
    {
        DisplayName = Name;
    }
}
```

**Comment by MichaelKetting** [comment]
@NigelWhatling: Thanks for the Exception details!

**Comment by retikanya** [comment]
Hello!
I also have a problem. I use AzureAD (AzureAD\username) user identification ...
Thank you for your work, very useful for us.

**Comment by FlorianDecker** [comment]
@NigelWhatling Thanks for the Details! I will probably have a look into the issue at the beginning of next month. We plan to try to change to whole thing from static to lazy loading and then add some error handling for the exception (maybe try the lookup a second time and if that fails giving a more meaningful error message)

**Comment by NigelWhatling** [comment]
@FlorianDecker Good to here. Lazy loading would be excellent. Particularly for what is potentially an expensive request like LDAP lookup. But exception handling at a minimum.  ;)

Great tool btw.

**Comment by hallambaker** [comment]
Is there any work-around I can use?

I really don't want to have to attach my computer to a domain just to get this working.

**Comment by FlorianDecker** [comment]
Hi hallambaker,

I dont think that there is a workaround for this in this version. :(   
But a fix is already on the way. We plan for a release as soon as possible, hopefully next week. 

Just out of interest: Do you get the exception when you are disconnected from the Internet? Because I cant reproduce it when being connected to the Internet, even when using a machine which is not in a domain.

**Comment by hallambaker** [comment]
I am connected to the Internet here. The machine is running Windows 10 and
is not in a domain.

**Comment by NigelWhatling** [comment]
@hallambaker @FlorianDecker I am happy to attach the workaround version I compiled if that helps until you're ready to put out an official release.

**Comment by hallambaker** [comment]
That would be very helpful. I am in the middle of releasing an open source
crypto project. Too many balls in the air already...

**Comment by NigelWhatling** [comment]
@hallambaker Here you go. https://www.dropbox.com/s/4vrfab7ucwr474q/LicenseHeaderManager.vsix?dl=0

**Comment by FlorianDecker** [comment]
@NigelWhatling your awesome! I did not think of that. Thanks for your support :)

**Comment by hallambaker** [comment]
Unfortunately, I am still getting the same exception.

I will try on my backup machine later today.

**Comment by FlorianDecker** [comment]
@hallambaker are you already on version 1.7? I think that it is not yet updated in the visual studio gallery.
