### ISSUE TITLE
I wrote an interim header manager, to be used until a VS2022 version of LHM gets released

### ISSUE THREAD

**Issue by squideyes** [rubicon-oss/LicenseHeaderManager#163]
**SetCodeHeaders** is a simple Visual Studio 2022 extension that does one thing and one thing alone: add text from a "\<Solution Name>.sln.headertext" file to ALL of the .CS, .XML, .CONFIG, .XSD and .XAML files in a given solution. 

The extension was written as a **stop-gap** while **waiting for Rubicon's superb License Header Manager** to be updated to work with VS2022, and should not be used as a long-term replacement, since:

- SetCodeHeaders does not support project-specific headers
- SetCodeHeaders does not remove header-text (although it does overwrite)
- SetCodeHeaders does not include localization support
- SetCodeHeaders does not have expandable properties
- SetCodeHeaders has not been well-tested (caveat emptor)

You can download the extension from [**https://github.com/squideyes/SetCodeHeaders**](https://github.com/squideyes/SetCodeHeaders)

Enjoy...

**Comment by MichaelKetting** [comment]
@squideyes Thank you for that update. Given that your ticket isn't a bug-report, feature-request (in and of itself), or a question, I'll be closing it. I recommend you contribute to the discussion in #141
