### ISSUE TITLE
Doesn't support Visual Studio 2015 Shared project

### ISSUE THREAD

**Issue by techcap** [rubicon-oss/LicenseHeaderManager#18]
it looks it doesn't support VS2015 Shared project template.
It said "Specified cast is not valid." in Shared Project.

**Comment by FlorianDecker** [comment]
Hi techcap!

Thanks for the bug report! I could reproduce your issue on my home computer but not here at work, so it will take some more time. 

I suppose we are talking about the C# Project Template? Just to make sure we are on the same line.

Regards,
Florian

**Comment by techcap** [comment]
Yes, C# shared project template.
Thanks.

**Comment by FlorianDecker** [comment]
Hi techcap!

Unfortunately I was not able to reproduce this issue on my home computer, it was a different error message and a completely different issue.

So I need more information from you on how to reproduce this issue. 

Can you reproduce the issue if you create a new Solution only containing a new shared Project and some .cs file?

If the answer to this question is yes, could you copy the value of your .sln containing the shared Project? (just open the .sln with a text editor and copy + paste it here). I just want to make sure we are speaking about the same Project Template.

Regards,
Florian

**Comment by techcap** [comment]
I used this solution. https://github.com/techl/core

Reproducing steps.
1. Open techl.sln with Visual Studio 2015
2. Right click Techl.Shared project in solution explorer.
3. click "Add License Headers to All Files"
4. Then the message is displayed. "Specified cast is not valid."

Thank you for your support.

**Comment by FlorianDecker** [comment]
Hi techcap!

Sry for the late reply. I was able to reproduce and fix it :) 
The Exception got thrown because of the folder inside of the shared project. 
We plan for the release of the next Version for next week.

Regards,
Florian

**Comment by techcap** [comment]
Thank you!!!

**Comment by techcap** [comment]
When will you release on VS Gallery?

**Comment by drauch** [comment]
Most probably before new year!

**Comment by drauch** [comment]
New version is up! :+1: 
https://visualstudiogallery.msdn.microsoft.com/5647a099-77c9-4a49-91c3-94001828e99e

**Comment by techcap** [comment]
Thank you!!!
