### ISSUE TITLE
Opens a temporary diff file

### ISSUE THREAD

**Issue by avdynut** [rubicon-oss/LicenseHeaderManager#187]
When compare files with built-in Visual Studio features, the extension opens a tab with a temporary file, more info here: https://developercommunity.visualstudio.com/t/Comparing-files-shows-a-temporary-file-f/10783182

**Comment by MichaelKetting** [comment]
@avdynut this might be a duplicate of #176

**Comment by avdynut** [comment]
@MichaelKetting Exactly, thanks

**Comment by MichaelKetting** [comment]
I'll close it as a duplicate then.
