### ISSUE TITLE
Inconsistent NewLine behaviour

### ISSUE THREAD

**Issue by FlorianDecker** [rubicon-oss/LicenseHeaderManager#19]
When adding a new file, LicenseHeaderManager inserts the LicenseHeader without an extra NewLine. 

When updating a file, LicenseHeaderManager inserts the LicenseHeader with an extra NewLine.

LicenseHeaderManager should either insert the extra NewLine every time or never.

**Comment by MichaelKetting** [comment]
* Up until now, LicenseHeaderManager would always add an additional newline at the end of the licenseheader when updating a licenseheader but not when inserting it into a new file.
* With this Patch, LicenseHeaderManager adds newlines exactly as they are defined in the .licenseheader file.
 * Exception: If there is a comment at the top of the file which is not part of the licensheader, it still adds a newline add the end of the inserted licenseheader to prevent making the already existing comment part of the licenseheader.
* Attention: Please review your .licenseheader file and update it if necessary. You may need to add an additional newline to the end of your licenseheaders, depending on your formatting.
