### ISSUE TITLE
1.6.3 update error 

### ISSUE THREAD

**Issue by FlorianDecker** [rubicon-oss/LicenseHeaderManager#20]
Sometimes when right clicking an ProjectItem after updating to 1.7.0, following Error Screen appears
![licenseheadermanagererror](https://cloud.githubusercontent.com/assets/13847286/12053579/ddea6ddc-af1a-11e5-8a5e-08f4d49a41b2.PNG)

It is not reproduceable 100%.

**Comment by MichaelKetting** [comment]
Were there changes to the settings in 1.7.0?

**Comment by FlorianDecker** [comment]
Not really, there was only some cleanup in the code (changing the license Headers and removing some unused usings). Also I am not sure where it got the 1.6.3 from, because this string does not occur anywhere in the solution. It is possible that just my Version is corrupt.
I will reinstall the extension and see if the error occurs again.

**Comment by MichaelKetting** [comment]
Hmm...yeah, sounds like something's wrong with the installation. Maybe something left over from a development build?

**Comment by FlorianDecker** [comment]
Duplicate of #44
