### ISSUE TITLE
Does not seem to work for ASP.NET 5 Projects

### ISSUE THREAD

**Issue by leastprivilege** [rubicon-oss/LicenseHeaderManager#21]
Returns error - 

"The system cannot find the file specified"

**Comment by FlorianDecker** [comment]
Hi leastprivilege,

thanks for the report! I can reproduce the issue locally and we will have a look into it.

Regards,
Florian

**Comment by leastprivilege** [comment]
thanks!

**Comment by drauch** [comment]
ASP.NET 5 projects are still in beta and not officially supported by LHM yet. However, we will have a look!

@leastprivilege: Do you experience any other LHM problems with "new" projects (e.g. .NET Core)?

**Comment by leastprivilege** [comment]
Well - strictly speaking they are in RC ;) Since this is the new OSS hotness it would be great if LHM would work with these project types.

automatically adding the header doesn't work either.

**Comment by FlorianDecker** [comment]
It seems like it does work with Asp.Net 5, at least on my work computer. Is it possible that you are plagued by the same bug like #22 ? 
You can try it out by using the plugin on any other project and it should throw the same error.

**Comment by leastprivilege** [comment]
yes seems to be the same issue.
