### ISSUE TITLE
Actual adding of header is not working

### ISSUE THREAD

**Issue by ravensorb** [rubicon-oss/LicenseHeaderManager#24]
I am working on adding headers to all of the files in one of the frameworks I am working on (https://github.com/XLabs/Xamarin-Forms-Labs) and I am trying to use the LHM to help with this however it is not working.  I have created the definition file and added it to my projects however when I go to actually add the header -- nothing happens (no error, no changes to the files, nothing).

Any idea on how I can track down what the issue is?

**Comment by drauch** [comment]
Do you have a branch pushed with the license header definition file included? We could then clone the repo and have a quick look :-)

**Comment by FlorianDecker** [comment]
Hi ravensorb!

Could you have a look at Options -> License Header Manager -> Languages? 
Are the Languages which you want to use in there?

**Comment by ravensorb** [comment]
As luck would have it -- yes I do :)

https://github.com/ravensorb/Xamarin-Forms-Labs

and yes, cs is the language I am working with and it is in there (and I referenced the cs extension in the header template)

Note: I just tried a "add license header to all projects" and VS2015 w/Update 1 crashed due to an out of memory error (hit 4gb of RAM before it crashed).

**Comment by MichaelKetting** [comment]
Just filed a bug for the All-Projects issue (#25). Had this myself a couple of days ago while updating a solution with 10.000 files.

**Comment by FlorianDecker** [comment]
@MichaelKetting which Version of VS did you use? To rule out VS2015 Update 1 as a cause.

**Comment by MichaelKetting** [comment]
VS2013 Premium.

**Comment by FlorianDecker** [comment]
Hi ravensorb!

I looked into your solution and you have an error in your .licenseheader file. The licenseheader has to be after the extensions line where you want to the licenseheader to be entered. 

So if you want to add licenseheaders the .cs, .cpp and .h files, you have to copy your licenseheader directly after the

    extensions: .cs .cpp .h
line

**Comment by MichaelKetting** [comment]
@ravensorb Did the suggestion by @FlorianDecker work or do you still have troubles with updating the file?

**Comment by MichaelKetting** [comment]
I'm closing this for now since it appears to not be a bug.
