### ISSUE TITLE
"Add license header to all projects" keeps consuming memory instead of releasing the resources after each file is done

### ISSUE THREAD

**Issue by MichaelKetting** [rubicon-oss/LicenseHeaderManager#25]
Use "Add license header to all projects" to add or update the license headers in a large solution and you can watch the devenv process continously adding memory while processing the files.

**Comment by FlorianDecker** [comment]
This happens because of the Resharper Extension. For 1.7.1 we will suspend Resharper before the solution gets updated.
 
In the future we will offer a more flexbile approach by adding configurable Pre/Post Commands (see #30).

**Comment by drauch** [comment]
Close the issue, or is there still a problem?
