### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by lfastrup** [rubicon-oss/LicenseHeaderManager#29]
I'm using version 1.7.0 with VS2015. When trying to add a new license header then I get the error "The system cannot find the file specified".

The project is a C# Class Library located in a folder named Source relative to the solution folder. The name of the project is different from source. It has the format Domain.Product. When adding a new license header definition file, it suggests the name as Source.licenseheader. I have tried renaming it to Domain.Product.licenseheader. But I get the error no matter what.

Any ideas how to resolve this?

**Comment by FlorianDecker** [comment]
Hi lfastrup!

It seems like you have stumpled over the same bug as #22 . Please look that thread up for a workaround. We are working on a fix.

Regards,
Florian

**Comment by MichaelKetting** [comment]
Resolved in 1.7.1.
