### ISSUE TITLE
License Manager hangs while Updating Files

### ISSUE THREAD

**Issue by squideyes** [rubicon-oss/LicenseHeaderManager#34]
Hi!

Using Visual Studio 2015 Enterprise Update 2, I've tried many times to get the LicenseHeaderManager to work, but it keeps on hanging.  It doesn't matter if I have source files open or closed, nor does mater if I use the generic .licenseheader file or create one of my own.

Any help in this regard would be greatly appreciated....

**Comment by FlorianDecker** [comment]
Hi squideyes,

what do you mean by hanging? Does it just not add the Header or does the UI freeze too?

And does it happen in any Project or in specific Projects?

**Comment by MichaelKetting** [comment]
Hi!
It's definitely doesn't look like a general issue - just did an update of a file in VS2015 Update2
~Michael

**Comment by squideyes** [comment]
Thanks for getting back to me.  I did an uninstall /reinstall, rebooted then created a new project and it worked.  Totally weird, but I’ll be sure to reach out if it happens again….

**Comment by FlorianDecker** [comment]
Nice! I'm glad it could be fixed that easy :) 

Regards,
Florian

**Comment by MichaelKetting** [comment]
Marked as 'invalid' until proven this is a recurring issue in LicenseHeaderManager.
