### ISSUE TITLE
.SQL files fail in VS 2013

### ISSUE THREAD

**Issue by jholliday** [rubicon-oss/LicenseHeaderManager#46]
Add the extension to VS 2013 Ultimate with SSDT project.  Right click SSAS project node => License Headers => Add new license header definition file.  Single extension (.sql) with simple header definition.

Edit a .SQL file.  Go to EDIT menu => Advanced => ? No command visible for inserting header.
Go back to project node - right click => License Headers => Options... => General => Link 'Add License Header' command to Before Edit.FormatDocument (Ctrl-E + Ctrl-D) => ? Nothing happens.  Try linking to other commands => Nothing happens.

**Comment by FlorianDecker** [comment]
Hi jholliday,

did you add .sql as Language in Tools->Optiones -> License Header Manager -> Languages?

**Comment by FlorianDecker** [comment]
As we are doing some housekeeping after the 2.0.0 release, i am going to close this issue due to low activity. If the problem was not solved with the proposed solution, feel free to comment, or open a new issue.
