### ISSUE TITLE
Extension keeps getting disabled

### ISSUE THREAD

**Issue by HenryMinute** [rubicon-oss/LicenseHeaderManager#51]
Using VS 2015 Community Edition. Windows 10

I have had LHM for some time and like it a lot but recently when I start VS, LHM is disabled. I enable it restart VS and LHM is there, but next time I start VS LHM is disabled once again.

**Comment by FlorianDecker** [comment]
Hi HenryMinute,

sounds like an weird Issue, thanks for reporting it.

I found a similar Problem in another VisualStudio Extension: https://github.com/madskristensen/WebEssentials2013/issues/1959

Could you try the steps provided there and report back if they worked?

Cheers,
Florian

**Comment by HenryMinute** [comment]
Thank you Florian.

I tried both remedies and it transpired that I had LicenseHeaderManager installed twice (apparently a common problem for extensions if you have more than one instance of VS running).

All now seems well. I used the tool written by Remco Ros [DuplicateExtensionFinder](http://david.gardiner.net.au/2015/11/web-essentials-2015-extension-keeps.html)
