### ISSUE TITLE
do not want .licenseheader file to proj

### ISSUE THREAD

**Issue by capqueen** [rubicon-oss/LicenseHeaderManager#52]
Any to remove .licenseheader file?
I think use the default header without the .licenseheader file is a good option.

**Comment by FlorianDecker** [comment]
Hi capqueen,

No, thats currently not possible and is not a planned feature. Why do you need this option? 

If you have multiple Projects and dont want to maintain multiple .licenseheader files, you can create one .licenseheader file and add it as link to the other Projects (Rightclick on Project -> License Headers -> Add Existing Licenseheader Definition File...).

**Comment by capqueen** [comment]
because .licenseheader can not share with team members. 
e.g. Author Name ... or other custom headers

**Comment by FlorianDecker** [comment]
Have you looked into [Expandable Properties](https://github.com/rubicon-oss/LicenseHeaderManager/wiki/Expendable-Properties)? You can use %UserName% or %UserDisplayName% to automatically add the Name of the current User into the Licenseheader.

Alternatively you could use the Extension Resharper, which offers adding of a Licenseheader text on top of files, which is defined in the Resharper Settings (see https://blog.jetbrains.com/dotnet/2010/12/20/automating-file-header-information-with-resharper/)

**Comment by FlorianDecker** [comment]
As we are doing some housekeeping after the 2.0.0 release, i am going to close this issue due to low activity. Feel free to comment, or open a new issue if there are any problems.
