### ISSUE TITLE
Header not working with linked files

### ISSUE THREAD

**Issue by felaugmar** [rubicon-oss/LicenseHeaderManager#53]
I'm working with linked files,
i.e.: My files "test.cs, test2.cs, etc", are outside of my project and I'm just linking then to my project.

I guess that this plug-in only update files inside the project and that's the why it's not working.

Well, has anyway? with linked files?

**Comment by FlorianDecker** [comment]
Hi felaugmar,

you are partly correct. For the LicenseHeaderManager to update Linked Files, the Files have to be in a Project in the same Solution. So we update only Files which are contained in the current Solution. 

If your linked files are in a Project in the same Solution, make sure that an .licenseheader File exists on either Solution Level, or in the Project where your linked Files are originally located.

I hope i could clear things up!

Regards,
Florian

**Comment by felaugmar** [comment]
So, with files outside of any project, I'll not be able to use the plug-in.

Any chance to this "behavior" exist in future releases?

**Comment by FlorianDecker** [comment]
We discussed this feature internally and there are some reasons which speak against it.

First, let me explain why we cant just use the .licenseheader file of the Project where the File is linked to:

Consider, as example, the possibility that the File is linked in multiple Projekt which have different .licenseheader files. This would mean that the linked file gets updated with any of the .licenseheader files (probably the last one, but depends on how you start the update).

In fact, this is how the LicenseHeaderManager handled Linked Files some updates ago. We changed that in 1.6.0, as we ran into the problem described above and wanted to have a more consistent handling of Linked Files.

Now, we could theoretically add the Licenseheader if all Projects where the File is linked to contain the same Licenseheader in the .licenseheader File. But this would increase Complexity and potentially performance, as we would have to check for every linked file, check if it is contained in any other Projects, check if the licenseheader matches etc.. While certainly doable, it is not really intuituve as the behaviour of a linked File would change, depending if the source File is added to the Solution somewhere or not.   


Now, how could you solve the Problem? You could add a .csproj to the Folder where the Source of your linked Files lies and add it to the Solution. 

Could you explain your Use Case on why you would need the feature? That would help us understanding on how the LicenseHeaderManager is expected to behave and maybe we find some way on how to make your Use Case work.

As example, while checking on how we currently handle Linked Files we found that we currently have your exact Problem with our AssemblyInfo Files, as we Link them into every Project and the original File lies in the Solution Root and is not added to any Project. 

In this case we decided that the AssemblyInfo File does not really contains any important Information, so it is not High Priority that it has the latest LicenseHeader Information. 

A Solution to the Problem would be adding a .csproj which contains the original AssemblyInfo File, link our existing .licenseheader File and add the whole thing to our Solution.

We are also thinking on maybe adding the Possibility to handle Items contained in Solution Folders. So in our case, we could add the original AssemblyInfo File into a Solution Folder together with a link to our .licenseheader File and would be good to go. Maybe this would help your case? 

This only helps if the Linked File lies somewhere around the Solution Directory Level. If the origin of your linked Files are somwhere else, you are best off using the Method described above (adding it to a .csproj File and link it to the Solution). 

But we are open for any Ideas on how to solve the Issue (considering the Points described above) :)

**Comment by FlorianDecker** [comment]
Small correction: You can add any item as solution item, they do not have to be at solution directory level. This would mean that our proposed change would help in most (?) cases.

So to summarize:

- Updating linked files where the original is not located in the solution is not going to be added
- As a workaround you can add the original file to a .csproj and add it to the solution. Add the desired .licenseheader to the new .csproj and the LicenseHeaderManager does update your linked Files
- We are planning to make this process easier by also searching for the original of linked items in the solution items (see #54 ). With this change you can just add the original file to your solution items, link some .licenseheader file into the folder and the LicenseHeaderManager does the updating.

**Comment by felaugmar** [comment]
I'll try to explain my situation.
Obs: I've changed it since the last comment I did, I've created a project to hold my files, instead of files alone.

> I'm using Virtual Studio in Windows through a Virtual Machine,
> my main OS is Linux and I'm sharing a folder between them.
> In that folder, resides my project created using [Monodevelop](http://www.monodevelop.com/).
> 
> What I'm doing is, I have a structure like 'Project/Folder1/Folder2/File.cs' in my Monodevelop project,
> I'm replying to the Visual Studio project the same folder structure 'Project/Folder1/Folder2/' and linking the file 'File.cs' in this directory.
> This way, when I change a file in Visual Studio project, it's the same file at Monodevelop project.
> 
> Obs: Both are different projects.

Now I see, the problem resides that I'm with both projects in different solutions (like you said), if I put then together, add the .licenseheader to the source project, it'll work.

Well, about your #54, I think it will be awesome, of course I'll use it when done, I guess that maintaining the files in "solution item" and just 'importing' then to the projects is the correct way in my case.

----

Just to explain the why of maintain two projects with Monodevelop and Visual Studio for the same thing.
> I'm doing that because projects created with Monodevelop don't works very well in Visual Studio, and vice versa.
> I don't know exactly why then don't work well, but for example, projects created with Visual Studio don't debug using Monodevelop and vice versa.
> Maybe if I change something, I could maintain just one project, but I don't found a way yet.
> 
> Maybe normal projects works in both (I haven't tested with then yet),
> I'm using [Monogame](http://www.monogame.net/) project template and probably the template for VS is different some way of the Monodevelop template, i need to check why and where it's different :confused: )

**Comment by FlorianDecker** [comment]
Seems like a complicated situation, but i am glad you got it to work! :)

As the issue seems to be resolved i am going to close the issue. Feel free to open a new one if you occur any problems with the LicenseHeaderManager.
