### ISSUE TITLE
Add support of VS2008

### ISSUE THREAD

**Issue by kolayuk** [rubicon-oss/LicenseHeaderManager#71]
Hi! It would be good to use your plugin to insert licence headers in VS2008

**Comment by MichaelKetting** [comment]
I've checked and I'm sorry but the earliest version we've ever supported was VS2010. You could take the last 1.6 release (https://github.com/rubicon-oss/LicenseHeaderManager/releases/tag/1.6.2) and go from there with downgrading to VS2008 by patching the manifest file and possibly downgrading the VS-AddIn dependencies.
