### ISSUE TITLE
ReSharper -> Refactor -> Adjust Namespace will insert blank line after license header

### ISSUE THREAD

**Issue by MichaelKetting** [rubicon-oss/LicenseHeaderManager#76]
Using ReSharper -> Reformat Code or LHM -> Add License Header will insert the license header without a blank line. 

Using ReSharper -> Adjust Namespace will introduce a blank line after license header.

**Comment by FlorianDecker** [comment]
Blank line is introduced by a ReSharper Setting. If the LicenseHeaderManager would be configured to run after the AdjustNamespace event, it would remove the blank line again (e.g. insert the LicenseHeader as configured in the .licenseheader file).
