### ISSUE TITLE
add dynamic month and year and some featuer

### ISSUE THREAD

**Issue by ghost1372** [rubicon-oss/LicenseHeaderManager#82]
hi tnx for  your great extension 💯 , i have some  suggestions 
~~Ability to put the month and year automatically~~ i found solution
~~ability to put project name and file name dynamicly~~ i found solution
Ability to put copy of license to root project (MIT, GPL, and more...)
Ability to put month like this: September, May, Feb,...
and please add some examples of licensing

**Comment by FlorianDecker** [comment]
Hi ghost!

Thanks for the review :)

You can put month, year, namespace and file name automatically via Expendable Properties: https://github.com/rubicon-oss/LicenseHeaderManager/wiki/Expendable-Properties .

Adding a copy of some of the popular licenses is currently not supported. We discussed the possibility and are going to draft a feature proposal, but probably wont implement it ourselves and leave it open for contribution. 

You can find examples of licensing on many places in the web like https://choosealicense.com/ or https://opensource.org/licenses .

Best Regards,
Florian

**Comment by ghost1372** [comment]
thank you @FlorianDecker  for your response.

**Comment by FlorianDecker** [comment]
See #83 for our feature proposal regarding adding popular licenses automatically. I see that you updated you suggestions. There are several wishes for the formatting of the Expendable Properties DateTime stuff, we will take your wish into consideration when we tackle the Expendable Properties issues.

**Comment by ghost1372** [comment]
ok tnx bro 👍
