### ISSUE TITLE
Package not loaded anymore in VS2017 V15.4.0

### ISSUE THREAD

**Issue by heering** [rubicon-oss/LicenseHeaderManager#84]
VS Acitivity Log is:
  <entry>
    <record>233</record>
    <time>2017/10/13 07:41:06.541</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [LicenseHeaderManager.LicenseHeadersPackage, LicenseHeaderManager, Version=2.0.2.0, Culture=neutral, PublicKeyToken=cdd89d39b9f20fb0]</description>
    <guid>{4C570677-8476-4D33-BD0C-DA36C89287C8}</guid>
  </entry>
  <entry>
    <record>234</record>
    <time>2017/10/13 07:41:06.562</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [LicenseHeaderManager.LicenseHeadersPackage, LicenseHeaderManager, Version=2.0.2.0, Culture=neutral, PublicKeyToken=cdd89d39b9f20fb0]Source: &apos;EnvDTE80&apos; Description: Unbekannter Name. (Ausnahme von HRESULT: 0x80020006 (DISP_E_UNKNOWNNAME))&#x000D;&#x000A;System.Runtime.InteropServices.COMException (0x80020006): Unbekannter Name. (Ausnahme von HRESULT: 0x80020006 (DISP_E_UNKNOWNNAME))&#x000D;&#x000A;   at EnvDTE80.Events2.GetObject(String Name)&#x000D;&#x000A;   at LicenseHeaderManager.LicenseHeadersPackage.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>
    <guid>{4C570677-8476-4D33-BD0C-DA36C89287C8}</guid>
    <hr>80020006</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>235</record>
    <time>2017/10/13 07:41:06.563</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [LicenseHeaderManager.LicenseHeadersPackage, LicenseHeaderManager, Version=2.0.2.0, Culture=neutral, PublicKeyToken=cdd89d39b9f20fb0](null)</description>
    <guid>{4C570677-8476-4D33-BD0C-DA36C89287C8}</guid>
    <hr>80020006</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>236</record>
    <time>2017/10/13 07:41:06.567</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [LicenseHeaderManager.LicenseHeadersPackage, LicenseHeaderManager, Version=2.0.2.0, Culture=neutral, PublicKeyToken=cdd89d39b9f20fb0]</description>
    <guid>{4C570677-8476-4D33-BD0C-DA36C89287C8}</guid>
    <hr>80020006</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by FlorianDecker** [comment]
It seems like this is an issue with your VS installation. Please try the steps described [on this site](https://developercommunity.visualstudio.com/content/problem/30312/problems-when-starting-vs-2017-enterprise-on-windo.html):

- Launch “Developer Command Prompt for VS 2017” as Administrator
- Go to VS 2017 installation folder, for example: pushd C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
- gacutil -if Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Shell.Interop.8.0.dll


if this does not work, maybe try the steps described [on this site](https://developercommunity.visualstudio.com/content/problem/26746/getting-errors-when-starting-vs2017-ide.html).

**Comment by kellybeth7** [comment]
A coworker and I are both having the same issue. The solutions above did not fix it. It is happening to me in VS 15.4.0 and 15.4.1. ActivityLog info is the same as previously reported. I did have Visual Studio 2015 installed as well (where License Header Manager was working fine). In my attempts to resolve this error, I have uninstalled VS 2015 and performed a repair on the VS 2017 installation, but it didn't help.

**Comment by FlorianDecker** [comment]
You could try deleting/renaming the ComponentModelCache Folder

It should be located under `%localappdata%\Microsoft\VisualStudio\15.0_d117062` (The hashvalue after "15.0_" probably is different on your machine)

**Comment by kellybeth7** [comment]
I've done that several times. Last time was just 5 mins ago. No luck.

**Comment by FlorianDecker** [comment]
I think i found the error location. Please uninstall your current LicenseHeaderManager version and try the version below:

[LicenseHeaderManager_unsigned.zip](https://github.com/rubicon-oss/LicenseHeaderManager/files/1415383/LicenseHeaderManager_unsigned.zip)

**Comment by kellybeth7** [comment]
That works! Thanks so much!

**Comment by FlorianDecker** [comment]
Nice!

Sry for the inconvenience!

**Comment by heering** [comment]
It works! Thanks for your support!

**Comment by FlorianDecker** [comment]
Nice! We will include the fix in the next official release :)
