### ISSUE TITLE
Chicken and egg issue when building the project from scratch

### ISSUE THREAD

**Issue by RandomEngy** [rubicon-oss/LicenseHeaderManager#86]
If you clone the repo, the LicenseHeaderManager project won't load due to a missing file from Microsoft.VisualStudio.Sdk.BuildTasks.14.0 . Also it doesn't pull in those files to the packages folder because the project hasn't loaded yet. I needed to manually pull in the package from the test project so that the main project would load.

**Comment by FlorianDecker** [comment]
Thanks for the info! :)
