### ISSUE TITLE
Trouble running VS experimental instance with F5

### ISSUE THREAD

**Issue by RandomEngy** [rubicon-oss/LicenseHeaderManager#87]
I'm trying to run/debug the extension by running an experimental instance of Visual Studio. In the Debug tab I set it up to run an external program:

    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe

With command line arguments

    "d:\mydocuments\Visual Studio 2017\Projects\TestConsoleApp\TestConsoleApp.sln" /rootsuffix Exp

This works with my extension but I'm not seeing the License Header Manager load in the experimental instance. I tried a bunch of stuff but nothing seems to work. Have you gotten this to work? Is there any trick? I'm using VS 2017.

**Comment by RandomEngy** [comment]
I got it deploying with F5 by swapping to Microsoft.VSSDK.BuildTools.15.5.72 . But breakpoints still aren't hit. There must be some other settings I'm missing...

**Comment by FlorianDecker** [comment]
Just so i know if the issue is resolved completely for you: Were you able to hit breakpoints with #88 ? I tested it on my machine and it worked correctly.

**Comment by RandomEngy** [comment]
Yes everything works fine now.
