### ISSUE TITLE
Problems with Python projects

### ISSUE THREAD

**Issue by SvitlanaLukicheva** [rubicon-oss/LicenseHeaderManager#93]
Hello,

I am using LicenseHeaderManager for my Python project and I am facing several issues:
- I cannot add a header file to .py files (same issue as in #40)
- so I tried "Automatically insert license headers in new files", but it does not work
- so I tried to link "Add license header" to several commands (such as "File.OpenFile" or "File.SaveSelectedItems"), but it does not work

The only way I found to add license files is at folders level, but it affects all the files of the selected folder (which is normal), but when I do it, a warning appears saying that my header definition contains non-comment text, (I have one line starting with '#', which corresponds to line comment in Python). I modified the symbol used for line comments in options, but I still have the warning and each time I insert headers at folders level, the previously inserted headers are not erased and I cannot remove them automatically.

I use Visual Studio Entreprise 2015.

**Comment by SvitlanaLukicheva** [comment]
Hello,

First of all I just noticed that I left the option "Only left comments containing at least one of the keywords below" enabled. I tried to disable it and now it partially works: my comment starting with '#' is correctly replaced, but the comment between '"""' is still not replaced.

The problem also happens when I create a new Python Project.

Here is my .licenseheader file:

![licenseheader](https://user-images.githubusercontent.com/17112177/33068340-391835f6-ceb1-11e7-9cc7-1ae3985cc537.png)

And here are my options:

![options1](https://user-images.githubusercontent.com/17112177/33068119-95a7332c-ceb0-11e7-8618-d29588a7ee73.png)
![options2](https://user-images.githubusercontent.com/17112177/33068121-982b592a-ceb0-11e7-85a8-3e8cdde0226d.png)

Finally, this is what happens when I add my license header twice:

![result](https://user-images.githubusercontent.com/17112177/33068320-26611248-ceb1-11e7-90d7-3e4e984d0e9e.png)

**Comment by FlorianDecker** [comment]
Thanks for your example!

We currently do not support empty lines in the middle of licenses in the definition file.
So an easy fix would be to remove the empty line and have your license header definition file like

    extensions: .py
    # -*-coding:Utf-8 -*
    """
    Here is my super license header
    """

I dont think that we can add support for that scenario, because we defined the licenseheader to end with the first empty newline or code. This way, it is possible to have additional comments, if wanted, between licenseheader and code.

But we should definitely improve the error message to inform the user that they should remove the newline. And also add that information to the documentation.

**Comment by FlorianDecker** [comment]
Alternatively you could comment the empty line

```
extensions: .py
# -*-coding:Utf-8 -*
#
"""
Here is my super license header
"""
```

**Comment by SvitlanaLukicheva** [comment]
It works, thank you! :)

Do you think there is a way to add headers to a particular file in my case? "Automatically insert license headers in new files" and linking commands don't seem to work, so my only option is adding it at folders level?

**Comment by FlorianDecker** [comment]
Sorry but the bug prevents our ability to find the correct definition file for files in folders. Until the bug #40 is fixed, there is no real workaround for that. The fix should be relatively straightforward, we just have to poke around with reflection to find the correct parent in the LicenseHeaderFinder. Sadly, i was not able to find the correct parent in a reasonable amount of time, so its currently on the backlog again. I will prioritize it the next time i get time for the project (which is probably sometime in the first half of next year).

**Comment by FlorianDecker** [comment]
I am closing this, as the issues are tracked in seperate issues.
